"""
AI Operating System - Execution Plan Models

The planner converts a resolved ParsedIntent into an
ExecutionPlan that can be safely executed by the OS.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class ExecutionStep(BaseModel):
    """
    A single executable action.
    """

    action: str
    parameters: dict[str, Any] = Field(default_factory=dict)


class ExecutionPlan(BaseModel):
    """
    Complete execution plan generated by the planner.
    """

    intent: str

    steps: list[ExecutionStep] = Field(default_factory=list)

    requires_confirmation: bool = False

    safe_to_execute: bool = True

    reasoning: str = ""

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC)
    )